// <auto-generated />
using FlyCraiovaSE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlyCraiovaSE.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250514201734_AddDestinationTable")]
    partial class AddDestinationTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlyCraiovaSE.Models.Destination", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Destinations");
                });

            modelBuilder.Entity("FlyCraiovaSE.Models.Plane", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Manufactured")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NrNormalSeats")
                        .HasColumnType("int");

                    b.Property<int>("NrPremiumSeats")
                        .HasColumnType("int");

                    b.Property<int>("NrSeats")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Planes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "https://images.aircharterservice.com/global/aircraft-guide/group-charter/airbus-a320-1.jpg",
                            Manufactured = 1994,
                            Model = "A320",
                            Name = "Airbus",
                            NrNormalSeats = 123,
                            NrPremiumSeats = 34,
                            NrSeats = 157
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "https://aircraft.airbus.com/sites/g/files/jlcbta126/files/styles/w640h512/public/2024-11/a321.png?h=3a37fd15&itok=WdLYVBok",
                            Manufactured = 1995,
                            Model = "A321",
                            Name = "Airbus",
                            NrNormalSeats = 156,
                            NrPremiumSeats = 31,
                            NrSeats = 187
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
