name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore OrganiseMe/OrganiseMe/OrganiseMe.csproj
    - name: Build
      run: dotnet build OrganiseMe/OrganiseMe/OrganiseMe.csproj --no-restore --configuration Release
    - name: Test
      run: dotnet test OrganiseMe/OrganiseMe/OrganiseMe.csproj --no-build --configuration Release --verbosity normal
